---
# Ansible will SSH into managed machines as this user
ansible_user: root

# Local user on the control machine
user: dimpo

# Home directory of the local user
home: /home/{{ user }}

# Name of the Python virtual environment
virtualenv: kubeflow-on-kvm

# Path to the Ansible Python interpreter
python_interpreter: |
  "{{ home }}/.pyenv/versions/{{ virtualenv }}/bin/python"

# Password for the root user on the managed machines
rootpw_hash: |
  $6$QDiGMXBTKPwTglrM$JJ4yRe4mw.SgPWVIOb/E/SYN5wQlRatEFR96NkHTqoBco334jh1pmulQ.Y64EAKc7KVNvepKdzWTjp5NxzjGz1

# SSH key for the root user on the managed machines
ssh_key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"

# Name of the VM host
vm_host: boogie

# Name of the PXE server
pxe_server: pxe-server

# Network configuration for the PXE server
dhcp_network: 192.168.122.0
dhcp_gateway: 192.168.122.1
dhcp_netmask: 255.255.255.0
dhcp_nameserver: 192.168.122.1
