---
- name: Create QEMU VMs
  hosts: qemu
  gather_facts: false
  roles:
    - role: qemu-vm
  vars:
    pxe_done: false

- name: Configure PXE Server
  hosts: pxe-server
  roles:
    - role: pxe-server

- name: Configure PXE Clients
  hosts: all:!admin
  gather_facts: false
  roles:
    - role: pxe-client

- name: Start QEMU VMs
  hosts: qemu
  gather_facts: false
  roles:
    - role: qemu-vm
  vars:
    pxe_done: true
