---
- name: Create QEMU VMs
  hosts: qemu
  tags: qemu-vm
  gather_facts: false
  roles:
    - role: qemu-vm
  vars:
    pxe_done: false

- name: Configure PXE Server
  hosts: pxe-server
  roles:
    - role: pxe-server
