---
- name: Create libvirt VMs
  hosts: libvirt
  gather_facts: false
  roles:
    - role: libvirt
  vars:
    pxe_done: false

- name: Configure PXE Server
  hosts: pxe-server
  roles:
    - role: pxe-server

- name: Configure PXE Clients
  hosts: all:!admin
  gather_facts: false
  roles:
    - role: pxe-client

- name: Start libvirt VMs
  hosts: libvirt
  gather_facts: false
  roles:
    - role: libvirt
  vars:
    pxe_done: true
